select
	ODR.OrderId as '1:お客様側管理番号'
	,'20250221' as '2:”­‘——\’è“ú'
	,'' as '3:”­‘——\’èŽžŠÔ‹æ•ª'
	,'' as '4:o‰×ŠúŒÀ“ú'
	,'' as '5:“ž’…ŠúŒÀ“ú'
	,'0' as '6:—X•ÖŽí•Ê'
	,'0' as '7:•Û—âŽí•Ê'
	,'0' as '8:Œ³^’…•¥^‘ãˆø'
	,'0' as '9:‘—¯^ƒZƒLƒ…ƒŠƒeƒB^“Á’è‹L˜^Ží•Ê'
	,'1100780 ' as '10:‘—‚èóŽí•Ê'
	,'' as '11:‚¨“Í‚¯æ ƒR[ƒh'
	,ODR.DeliveryZipcode as '12:‚¨“Í‚¯æ —X•Ö”Ô†'
	,ODR.DeliveryState as '13:‚¨“Í‚¯æ ZŠ‚P'
	,ODR.DeliveryCity as '14:‚¨“Í‚¯æ ZŠ‚Q'
	,ODR.DeliveryAddress1 + isnull(ODR.DeliveryAddress2,'') as '15:‚¨“Í‚¯æ ZŠ‚R'
	,ODR.DeliveryName as '16:‚¨“Í‚¯æ –¼Ì‚P'
	,'' as '17:‚¨“Í‚¯æ –¼Ì‚Q'
	,'0' as '18:‚¨“Í‚¯æ ŒhÌ‹æ•ª'
	,replace(ODR.DeliveryPhone,'+8180','080') as '19:‚¨“Í‚¯æ “d˜b”Ô†'
	,ODR.DeliveryMail as '20:‚¨“Í‚¯æ ƒ[ƒ‹ƒAƒhƒŒƒX‚P'
	,'0' as '21:‚¨“Í‚¯æ ‹Ç—¯‚ß‹æ•ª'
	,'' as '22:‚¨“Í‚¯æ ‹Ç—¯‚ß—X•Ö‹Ç–¼'
	,'' as '23:‚¨“Í‚¯æ ‹Ç—¯‚ß—X•Ö”Ô†'
	,'0' as '24:‚¨“Í‚¯æ ‹Ç—¯‚ßƒ[ƒ‹—˜—p‹æ•ª'
	,'0' as '25:‚¨“Í‚¯æ ”z’B—\ƒ[ƒ‹—˜—p‹æ•ª'
	,'0' as '26:‚¨“Í‚¯æ Ä”z’B—\ƒ[ƒ‹—˜—p‹æ•ª '
	,'' as '27:‚²ˆË—ŠŽå ƒR[ƒh'
	,'436-0082' as '28:‚²ˆË—ŠŽå —X•Ö”Ô†'
	,'Ã‰ªŒ§Š|ìŽs' as '29:‚²ˆË—ŠŽå ZŠ‚P'
	,'’W—z' as '30:‚²ˆË—ŠŽå ZŠ‚Q'
	,'18”Ô1' as '31:‚²ˆË—ŠŽå ZŠ‚R'
	,'ƒeƒB[ƒ‰ƒCƒtŠ”Ž®‰ïŽÐ' as '32:‚²ˆË—ŠŽå –¼Ì‚P'
	,'' as '33:‚²ˆË—ŠŽå –¼Ì‚Q'
	,'0' as '34:‚²ˆË—ŠŽå ŒhÌ'
	,'0547462232' as '35:‚²ˆË—ŠŽå “d˜b”Ô†'
	,'' as ' 36:‚²ˆË—ŠŽå ƒ[ƒ‹ƒAƒhƒŒƒX‚P'
	,'0' as '37:‚²ˆË—ŠŽå ‚¨“Í‚¯’Ê’mƒ[ƒ‹—˜—p‹æ•ª'
	,'0' as '38:‚²ˆË—ŠŽå ‚¨“Í‚¯’Ê’m‚Í‚ª‚«Žg—p‹æ•ª'
	,'' as '39:Žó’”Ô†'
	,'' as '40:’•¶“ú'
	,'1' as '41:‚±‚í‚ê‚à‚Ì‹æ•ª'
	,'0' as '42:‚È‚Ü‚à‚Ì‹æ•ª'
	,'1' as '43:ƒrƒ“—Þ‹æ•ª'
	,'1' as '44:‹t‚³‚ÜŒµ‹Ö‹æ•ª'
	,'0' as '45:‰ºÏ‚ÝŒµ‹Ö‹æ•ª'
	,'80' as '46:¤•iƒTƒCƒY^d‚³‹æ•ª'
	,PRD.Weight as '47:d—Ê‡Œvi‚‡j'
	,'' as '48:‘—¯@‘¹ŠQ—vžŠz'
	,'0' as '49:‘¬’BE”z’B“úŽw’èŽí•Ê'
	,'' as '50:”z’BŽw’è“ú^Šó–]“ú'
	,'00' as '51:”z’BŽžŠÔ‘Ñ‹æ•ª'
	,'0' as '52:‚ä‚¤ƒpƒbƒN•¡”ŒÂŠ„ˆø'
	,'0' as '53:‚ä‚¤ƒpƒbƒN“¯ˆêŠ„ˆø'
	,'' as '54:•¡”ŒÂŒû”'
	,'H•i‹l‚ß‡‚í‚¹' as '55:‹LŽ––¼‚P'
	,'' as '56:‹LŽ––¼‚Q'
	,'' as '57:ƒtƒŠ[€–Ú‚O‚P'
	,'' as '58:ƒtƒŠ[€–Ú‚O‚Q'
	,'' as '59:ƒtƒŠ[€–Ú‚O‚R'
	,'' as '60:ƒtƒŠ[€–Ú‚O‚S'
	,'' as '61:ƒtƒŠ[€–Ú‚O‚T'
	,'' as '62:ƒtƒŠ[€–Ú‚O‚U'
	,'' as '63:ƒtƒŠ[€–Ú‚O‚V'
	,'' as '64:ƒtƒŠ[€–Ú‚O‚W'
	,'' as '65:ƒtƒŠ[€–Ú‚O‚X'
	,'' as '66:ƒtƒŠ[€–Ú‚P‚O'
	,'' as '67:‘ãˆø‹àŠz'
	,'' as '68:‘ãˆøÁ”ïÅ‹àŠz'
	,'H•i‹l‚ß‡‚í‚¹' as '69:•i–¼'
from Orders ODR
inner join OrderDispatches ODP
on ODR.OrderId=ODP.OrderId
and ODP.IsDeleted='0'
inner join OrderDispatchProducts ODD
on ODP.OrderId=ODD.OrderId
and ODP.DeliveryId=ODD.DeliveryId
and ODD.IsDeleted='0'
inner join Products PRD
on ODD.ProductCode=PRD.ProductCode
where 0=0
--and ODR.OrderStatus in('30')
--and ODR.OrderStatus not in('40','99')
and ODR.IsDeleted='0'
and ODP.DeliveryCompanyCode in('JP-YP')
order by ODD.ProductCode,ODR.OrderName
;
